### ISSUE TITLE
b. usp_UpdateDepartmentName(DNumber, DName)

### ISSUE THREAD

**Issue by joamla96** [jona8690/DBD-Compulsory-Assignment-1#2]
If the new name is not already is use,The DName is updated to the new value.
Else, an SQLException is thrown.

**Comment by patrickhansen12** [comment]
USE Company;
GO
CREATE FUNCTION usp_DepartmentNameExists(@DName VARCHAR(MAX))
	RETURNS BIT
	AS
	BEGIN
		IF EXISTS(SELECT * FROM [dbo].[Department] WHERE DName = @DName)
			RETURN 1;
		ELSE
			RETURN 0;
		
		RETURN 0;
	END

GO

GO
CREATE PROCEDURE usp_UpdateDepartmentName(
	@DNumber INT,
	@DName VARCHAR(50)
)
AS
BEGIN
	BEGIN TRANSACTION
	DECLARE @err_message nvarchar(MAX)
	
	IF (dbo.usp_DepartmentNameExists(@DName) = 1)
	BEGIN
			RAISERROR('A Department with name already exists', 16, 1);
	END

	UPDATE [dbo].[Department]
	SET 
		[DName] = @DName
	WHERE
		DNumber = @DNumber
END
